name: uploadToTestFlight

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DEVELOPER_DIR: /Applications/Xcode_12.3.app
    
jobs:
  build:

    runs-on: mocos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Show Xcode version
      run: xcodebuild -version
      
      
